### ISSUE TITLE
XCM Support

### ISSUE THREAD

**Issue by mustermeiszer** [centrifuge/fudge#15]
Currently the library does not support XCM transfers. The reasons for the missing capabilities is, that it would essentially require a "correct" interaction between relay-chain and parachain. The current approach is rather force-setting the head of the parachain on the relay-chain side to the latest known head retrieved from the parachain. 

## Tasks
- [ ] Wait for #13 to be closed / or implement a hack that xcm messages are inserted into the correct quees and taken from the correct queues (probably evenly hard...)
- [ ] Implement an actual storage for messages on the builder side
- [ ] Inject those xcm messages into the queues on the respective chain side-state (xcm messages are not as extriniscs, and one can not assume that xcm-pallet is available, but parachain-system MUST be available so use these quees directly)

**Comment by mustermeiszer** [comment]
Mostly done in https://github.com/centrifuge/fudge/commit/ad4cf5e472530048941670d1268fa70b55f39604
